apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv-hive-postgresql
spec:
  capacity:
    storage: 8Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: data-my-hive-postgresql-0
    namespace: default
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: hive-postgresql
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /hadoop4/kubernetes-volumes
    server: IP
